# Generated by Django 2.1.4 on 2018-12-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walletmodel',
            options={'ordering': ['-wallet_type', '-created'], 'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='spent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
