# Generated by Django 2.1.4 on 2018-12-13 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_depositmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositmodel',
            options={'ordering': ['-created'], 'verbose_name': 'Deposit', 'verbose_name_plural': 'Deposits'},
        ),
        migrations.AlterField(
            model_name='depositmodel',
            name='value',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='walletmodel',
            name='value',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
